### ISSUE TITLE
Could you add more Genres, or give us the option to add them ourselves? 

### ISSUE THREAD

**Issue by Muthabuffer** [Theo47/depressurizer#100]
Hi,

Firstly just want to say I love this tool it's amazing, I have over 1000 games and it's helping me make sense of the mess.

There is one thing however I'm finding frustrating, the auto-categorise tool is amazing but it becomes a bit useless without the Genre you want available to you in the Edit Autocats screen. 

Could you add more common Tags to the Genres so they can be auto categorised? or give us the option to add our own?

It's a bit weird I can categorise by Gore and Nudity but not things like FPS, Puzzle, Platformer, Puzzle-platformer, Third Person, Point & Click, Hidden Object etc.

Thanks in advance, and not meant as a criticism. If I am being dumb and you can do this I'd appreciate any help.

**Comment by Theo47** [comment]
That's more of a steam thing.
![steam genres](https://cloud.githubusercontent.com/assets/12672701/23990342/6c194130-0a3e-11e7-8bf4-57a153f90f7a.png)
On the genres field, steam only has the "genres" you see on the "edit autocats" screen and it doesn't use any other tags.

You can create a tags autocat to autocategorize using tags though.

**Comment by Muthabuffer** [comment]
Oh my god I'm so dumb didn't realise you could do that, thank you! :)
