### ISSUE TITLE
Crash at the startup

### ISSUE THREAD

**Issue by Althorion** [Theo47/depressurizer#103]
Depressurizer crashes at startup.

Error Details
Error type: `FormatException`
Error Message: `Ciąg nie został rozpoznany jako prawidłowy element DateTime.`
(translation from Polish: string was not recognized as valid DateTime element)
Stack Trace:
```
FormatException: Ciąg nie został rozpoznany jako prawidłowy element DateTime.
   w System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   w System.Convert.ToDateTime(String value)
   w Depressurizer.Profile.AddGameFromXmlNode(XmlNode node, Profile profile, Int32 profileVersion)
   w Depressurizer.Profile.Load(String path)
   w Depressurizer.FormMain.LoadProfile(String path, Boolean checkForChanges)
   w Depressurizer.FormMain.FormMain_Load(Object sender, EventArgs e)
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.ContainerControl.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.Form.WndProc(Message& m)
   w MaterialSkin.Controls.MaterialForm.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

To replicate: unzip and try to run the application.
Observed behaviour: application crashes.
Wanted behaviour: flawless startup.

EDIT:
Workaround: Change Time/Date format settings until you find one that works.

**Comment by CorruptComputer** [comment]
Uh... Works fine for me, OS?

**Comment by Althorion** [comment]
Windows 10 Pro N, 64-bit

**Comment by CorruptComputer** [comment]
I have no clue, it could have something to do with the N variant of Windows 10, as some features are not included. 
Have you tried reinstalling .NET? https://www.microsoft.com/en-us/download/details.aspx?id=40779

**Comment by Althorion** [comment]
Now I have, but no dice.

I’d rather blame Polish language version than N, because I have Media Feature Pack installed and things that normally require it (i.e. ADM ReLive) work just fine.

Or it could be something connected to recent Windows Updates, since it used to work for me about a month ago, on 0.7.1.4, and now neither that nor the most recent version work.

**Comment by CorruptComputer** [comment]
Hmm, it's working fine for me and I'm on the Creators update. So I don't think that is to blame. I honestly have no idea what could be causing this.

**Comment by Althorion** [comment]
Changing Date/Time format to the one used in the USA helped (I tend to use ISO standard). Plus, quick googling of the problem suggested using `CultureInfo.InvariantCulture` with `DateTime.ParseExact`: [[1]](http://stackoverflow.com/questions/2193012/string-was-not-recognized-as-a-valid-datetime-format-dd-mm-yyyy) [[2]](http://stackoverflow.com/questions/30083075/string-was-not-recognized-as-a-valid-datetime-exception-with-datetime-praseexact) [[3]](http://stackoverflow.com/questions/17870854/the-string-was-not-recognized-as-a-valid-datetime-formatting).

**Comment by Theo47** [comment]
Fixed. 31f93d6894d7ccd4ebac63e8f5d1ed8b3634dcd2
