### ISSUE TITLE
[Suggestion] Support multi-line text display in game list

### ISSUE THREAD

**Issue by jaege** [Theo47/depressurizer#107]
Currently, every game in list display its game banner and information in just single line. It's ok for columns like year and review rates, but for very long column like tags, flags and genres, the width is really not enough. Since the banner height is almost the same as 3 lines' height, I think it would be better to support multi-line text in game list (2 lines is enough).

Before:
![multi-line_text_b4](https://cloud.githubusercontent.com/assets/5965757/26024343/05409368-3802-11e7-8cb5-985f8d7bd5e2.jpg)

After:
![multi-line_text_af](https://cloud.githubusercontent.com/assets/5965757/26024346/0f900cfe-3802-11e7-8968-240bb99a2cc9.jpg)

**Comment by Theo47** [comment]
Enabled Word Wrap for Categories, Flags, Tags and Genres columns. d8d8bf51a570f3a0988dfc6270c4d27237465931

![word wrap](https://user-images.githubusercontent.com/12672701/27763066-5fac13f0-5e85-11e7-926b-0049bd463a83.png)
