### ISSUE TITLE
My issues from rallion's repo

### ISSUE THREAD

**Issue by CorruptComputer** [Theo47/depressurizer#11]
I know if I just leave them there they will never get fixed, so I am just gonna link them here:

https://github.com/rallion/depressurizer/issues/37
https://github.com/rallion/depressurizer/issues/21

**Comment by Theo47** [comment]
Is there a problem with rallion#37? I thought the database was out of date only cause u needed to update it manually.

**Comment by CorruptComputer** [comment]
For 37 the problem I had was that store pages are getting updated, but not rescraped.

For 21 those games do not scrape correctly because they have no store page or they have been removed from steam. This could be fixed with parents being set manually, but even when parents are set the children don't inherit the tags from them.

**Comment by Theo47** [comment]
Well if you choose a game in the database and select "scrape selected", it will rescrape it using the current steam store page. So still not sure what i should fix on 37.

I'll take a look at games with no steam store page inheriting their parent's tags.

If you are willing to make a list of game ids and their parent ids for the games that need a manual setting of parents, i could add them manually.

**Comment by CorruptComputer** [comment]
With 37 is there a way to check of the store page has been updated since that game was last scraped?

Also, I can do what is in my library for the child/parents, but other than that I have no idea.  Also an option to hide games that are hidden in steam would be great.

**Comment by Theo47** [comment]
I don't think there is a way to see if a store page got updated apart from visiting the store page which is what scraping a game in the database editor already does.
I could add something like when you try to autocategorize a game, if it hasn't been scraped in the last x days, it would ask you if you want to scrape it right now.

I took a look at games with empty database entries inheriting their parent's tags and it seems it is already implemented and working. If you try to autocategorize a game that has no tags/flags/genres but has a parent, it will use the parent's tags/flags/genres instead to autocategorize it. It doesn't seem to work for review score and release date though.
I could have those inherit too but i don't know if that would make sense for release year. If we are talking about dlcs, i imagine those would be released at a different date than their parents.

I don't know how motivated i feel about manually adding the parents to the code if it is only a few games. It just feels simplier directly adding them to the database instead.

Hiding hidden games sounds kinda obvious so ill do that.

**Comment by HunterZ** [comment]
It may be more a ideal design to have a master server somewhere do a daily (or even more frequent) scrape and serve up scraped data as a versioned bundle to depressurizer clients. That way users never need to go through a long re-scrape operation to be sure they have the latest data.

The only problem is that the scrape operation needs to run somewhere, and the scraped data needs to be hosted somewhere. I suppose a home or Internet server could do the scraping and put the data here on Github.

**Comment by CorruptComputer** [comment]
I could look into making a scrape server if you would like, I don't think it would be that difficult. I could have it scrape everything every night at midnight.

**Comment by Theo47** [comment]
Sure, that sounds like a great idea!

**Comment by Theo47** [comment]
@CorruptComputer So did you take a look at making a scrape server?

**Comment by CorruptComputer** [comment]
Yeah, is it possible for you to A) compile to linux and B) take command line arguments?

**Comment by Theo47** [comment]
Taking command line arguments shouldn't be a problem. I know that depressurizer already accepts command line arguments for autocategorizing a game (automode) so it shouldn't be hard to build on that and add another command for scraping the database or something.

Now i have no idea how to compile to linux and what that requires so that can be a problem.

**Comment by CorruptComputer** [comment]
Well if you could get it to compile to linux I might be able to get Travis CI to run it anytime you commit. But other than that it would need money to get a server.

**Comment by Theo47** [comment]
Does that mean that the database would only get updated when i make a new commit?
I don't really trust on me making regular commits so i don't know how useful that will be.

**Comment by CorruptComputer** [comment]
Then the only solution I have found is to rent a server from somewhere and run it there.

**Comment by Theo47** [comment]
Renting a server would cost money so that doesn't sound like a practical solution either.
I guess i will put the server thing on ice for now due to lack of a good solution.
I might revisit the idea of hosting it in my home computer in the future though.

**Comment by CorruptComputer** [comment]
Alright, so then I would call this closed.
