### ISSUE TITLE
I change language but doesn't happen anything.

### ISSUE THREAD

**Issue by BanCrash** [Theo47/depressurizer#114]
Hello, I change the language on the program but it doesn't make any change. I'm using the last release (Depressurizer 0.7.2.0) and have the .NET Framework 4.5.1 installed.

I restart the program after changing the language but it still the same. I tried also with all the other languages and no change happens...

However when I restart it shows in the language the language I selected, so it isn't a problem of the program doesn't accept the change:

![image](https://user-images.githubusercontent.com/11770760/27828873-d36ddd1a-60be-11e7-9c17-f14140868b87.png)

**Comment by BanCrash** [comment]
Sorry, I send it without description by mistake. Now it have description.

**Comment by mvegter** [comment]
@BanCrash Which version or you running? Or did you compile it yourself?

**Comment by BanCrash** [comment]
@mvegter I'm using the last release (Depressurizer 0.7.2.0) and have the .NET Framework 4.5.1 installed.

**Comment by mvegter** [comment]
@BanCrash @Theo47 Confirmed not working!

**Comment by Theo47** [comment]
Yeah also doesn't work for me when using the latest release. Works when i compile it myself.

Best guess is that i forgot to merge some of the dlls when making that release. So next release this should be fixed.
