### ISSUE TITLE
Auto Cat only One new category

### ISSUE THREAD

**Issue by Claona** [Theo47/depressurizer#116]
Hi,

To begin with, sorry for my bad mastery of the English language.

I used this (SUPER) program to auto-cat my l steam library. Then i changed a lot of things manually. Then I realized that I had forgotten to auto-cat categories. I would like to know if I can add a category and automatically add games in, and just in this one?
For example, I forgot the category "Management", can we create a category and ask to add only the games containing the tag "management" without modifying all the other categories or go each game manually ?

Thanks !

**Comment by Theo47** [comment]
You can edit autocats if you go to Profile->Edit autocats.

If you go to the tag autocat and only check the management tag, it will do what you said on your example.
