### ISSUE TITLE
Creating genre categories with no games in it when prefix used

### ISSUE THREAD

**Issue by ppriest** [Theo47/depressurizer#13]
I have a "By Genre" profile. Everytime I 'autocat all' it recreates the cats sans prefix as well as with, and assigns zero games to it.
Doesn't appear to affect flags/years/HLTB, only Genres.

**Comment by Theo47** [comment]
I think this may have to do with "autocat all" also autocategorizing hidden games.

Can you verify if this is the case? See if you have any hidden games that would fit those genres.

I'll see about making "autocat all: not autocategorise hidden games

**Comment by ppriest** [comment]
I have hundreds hidden, though if that's the cause then it just implies there's another codepath for them that isn't treating the prefix consistently surely? Might as well fix that unless there's a perf problem with tagging hidden.

**Comment by Theo47** [comment]
Wait, did you meant that it creates both a category with and without the prefix at the same time? Like it creates both a category named "action" and a category named "(prefix) action"?

Hidden games would explain why it creates some categories with zero games but not why it would create a category with both with and without the prefix simultaneously.

Also id expect it to treat the prefix consistently. If it creates a category with 0 games when you use a prefix then it should also create a category with 0 games if you dont use a prefix. Is this not happening?

There shouldn;t be any perf problem tagging hidden. I just figured out that if you hid a game then you probably dont want to categorize it.

**Comment by ppriest** [comment]
> Like it creates both a category named "action"
> and a category named "(prefix) action"?

Yup, that is what is happening. Only afflicts the genre autocat though. I've since moved to use purely tags though, but since the default profile is By Genre I figured it was worth mentioning.

**Comment by Theo47** [comment]
In that case i still have been unable to replicate this and i couldn't find anything on the code to explain this so i'll need more information to try to narrow the cause.

Is creating the categories both with prefix and without happening for all genre categories or only some of them?
Is assigning 0 games to categories happening for all genre categories or only some of them?

Also could you use the previous version and see if that still happens?
If it still happens can you also use rallion's latest version too then?

**Comment by ppriest** [comment]
I was going to try and debug it when I realised I've now deleted the 'By Genre' from my profile and don't have a backup. I've recreated it and it's no longer occurring, so I put it down to either corrupt config or bad process state.
