### ISSUE TITLE
When adding new userscore/HLTB autocat "Rule", minor UI issue

### ISSUE THREAD

**Issue by ppriest** [Theo47/depressurizer#14]
When adding a new Autocat rule for the UserScore/HLTB cases, the new Rule is highlighted in the list, but you need to click it again to correctly select it and enable the widgets for the rule parameters.

**Comment by Theo47** [comment]
When i tried it, no rule seemed to be highlighted after adding a new autocat rule.

Still i guess it makes sense to highlight the new rule so i'll see about adding it once i have more time.

**Comment by EnemyWithin** [comment]
This is working correctly in my latest build.
