### ISSUE TITLE
Use more sites for scraping

### ISSUE THREAD

**Issue by mvegter** [Theo47/Depressurizer#142]
Games like Dirt 3 Complete Edition are not catergorized due to not having a store page, you could use websites like SteamDB and scrape from there.

**Comment by DannyDaemonic** [comment]
Scrapers aren't allowed with SteamDB:
https://steamdb.info/faq/#can-i-use-auto-refreshing-plugins-or-automatically-scrape-crawl-steamdb
> We also do not allow scraping/crawling on SteamDB. Please get the information from Steam itself using SteamKit and/or the Storefront API.
