### ISSUE TITLE
Chance of ability to select language used by auto-cat?

### ISSUE THREAD

**Issue by Zhuinden** [Theo47/depressurizer#157]
`Genre` auto-cat used to get the genre for me in English, but now it's being a prick and fetches them in Hungarian. (I live in Hungary, of course).

Is there any way to somehow make Steam not get the tags in hungarian? This makes the genre autocat inconsistent for me, which is pretty bad.

**Comment by kmicki** [comment]
Set preffered language in Tools->Settings->Steam Store Language
After that use Auto-Cat.

**Comment by Zhuinden** [comment]
@kmicki awesome, thank you!
