### ISSUE TITLE
Can I revert to the original Steam config file?

### ISSUE THREAD

**Issue by jciurc** [Theo47/depressurizer#167]
I prematurely exported my profile and ruined my whole steam library organization. Where is the config file located? Does it make a backup before replacing? Is there a way I can revert to what I had before running this?

**Comment by mvegter** [comment]
@symphony Yes there is. In Depressurizer if you click on Profile -> Restore Steam Config you can select up to the three last saved changes.

This is an inactive repo, you can check my fork of Depressurizer.
- [Source code](https://github.com/mvegter/Depressurizer)
- [Latest release](https://github.com/mvegter/Depressurizer/releases/latest)

**Comment by jciurc** [comment]
Thank you very much :) 

I'm going to update to your repo
