### ISSUE TITLE
Enhancement: link external game to steam game for categorization

### ISSUE THREAD

**Issue by scowalt** [Theo47/depressurizer#25]
I own Far Cry 3 on UPlay and have it listed as a non-Steam game on Steam. It would be great to be able to say to Depressurizer "This external application is the same as Steam app [220240](http://store.steampowered.com/app/220240/) for categorization purposes." Then, for all auto-categorization jobs, Depressurizer will use the data from 220240 to categorize the app.

Thanks for keeping this project alive!

**Comment by EnemyWithin** [comment]
Use the context menu in the game list to "Add New Game..."  Enter the Steam ID and Name and it will do what you are asking.  At the moment you can't launch the game though.  I'll fix that.

**Comment by scowalt** [comment]
Thanks for the suggestion!

This falls short in that it doesn't categorize the shortcut in Steam (just manually adds an entry in the Depressurizer DB). Regardless, this works for now.

**Comment by EnemyWithin** [comment]
Just committed new version that has an executable field for each game.  Setting the value will load the executable instead of trying to launch through Steam.

**Comment by EnemyWithin** [comment]
Also, there is code to import and export Steam shortcuts.  I'm not sure if it's working though.

**Comment by scowalt** [comment]
Just had a chance to try out the latest build: the executable field isn't writable for me. Demo:

![output](https://cloud.githubusercontent.com/assets/1100550/13205715/fdf97a6c-d8a2-11e5-93c4-28dd0eafb157.gif)

Thoughts?

**Comment by EnemyWithin** [comment]
I didn't realize that Uplay had their own launch prefix.  I check to make sure the file exists before saving the executable.  I'll change that for the next release.

**Comment by scowalt** [comment]
Latest release fixes the uPlay launching issue. I'll go ahead an close this issue, as it's really close to what I had in mind. Thanks for working on this!
