### ISSUE TITLE
0.7.0.0 won't start for me

### ISSUE THREAD

**Issue by ppriest** [Theo47/depressurizer#29]
Immediately crashes on startup with the following stacktrace in the log:
14:34:27.716864 -  ERR: Erroring saving game banner to C:\Users\tourn\Desktop\depressurizer-0.7.0.0\Game Banners\4000.jpg.
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
   at System.Drawing.Image.Save(String filename)
   at Depressurizer.Utility.GrabBanner(Int32 id)
14:34:33.021942 - INFO: Program closing.

This is on a Surface Pro 3 running patched Win10.

**Comment by ppriest** [comment]
Hrm, moved it to another location outside Desktop and it was okay. It still logged a similar exception though in the new location, so I guess that was unrelated.

**Comment by EnemyWithin** [comment]
That's the first run bug.  It will be fixed shortly.

**Comment by EnemyWithin** [comment]
Do all the other game banners save ok?  4000 is Gary's Mod.  Does it display a banner for Gary's Mod?

**Comment by ppriest** [comment]
A few others failed too:
280, 300, 320, 340, 360, 380, 2370
Sooo, early Valve plus a Hexen expansion.

Yes, banners for these titles appear to display now so I guess it managed to get them on a retry.

**Comment by ppriest** [comment]
Related, I just noticed more errors in the log repeatedly retrieving images from the CDN:

15:49:55.839215 - WARN: Erroring getting image from https://steamcdn-a.akamaihd.net/steam/apps/12230/capsule_sm_120.jpg.
15:49:55.865265 - WARN: Erroring getting image from https://steamcdn-a.akamaihd.net/steam/apps/12240/capsule_sm_120.jpg.
15:49:55.888370 - WARN: Erroring getting image from https://steamcdn-a.akamaihd.net/steam/apps/12250/capsule_sm_120.jpg.
15:49:56.191245 - WARN: Erroring getting image from https://steamcdn-a.akamaihd.net/steam/apps/39530/capsule_sm_120.jpg.

**Comment by EnemyWithin** [comment]
Yes, those are games without banners.  You can ignore the warnings.  I should probably add an IGNORE game list for retrieving banners to avoid those messages.

**Comment by Theo47** [comment]
I assume this is fixed now too. Feel free to correct me if i am wrong.
