### ISSUE TITLE
Autocat by htlb

### ISSUE THREAD

**Issue by Theo47** [Theo47/depressurizer#3]
Consider whether it would be a good idea to add autocat by howlongtobeat.com completion times.

**Comment by wickles** [comment]
Autocat by DRM (uplay, rockstar, securom, tages, etc) would be nice too. Probably best done just by scraping, Enhanced Steam already does this with a simple keyword search in the store description, see their repo for details.

**Comment by Theo47** [comment]
[This](http://www.howlongtobeatsteam.com/#/cached/all) looks like a good site to scrape for the htlb times since it pairs steam id with htlb id for all games and displays them in a convenient form.

**Comment by Theo47** [comment]
I'll take a look at Autocat by DRM later on. If you just need to scrape the store page for the info then i don't see any drawback in adding it but it is a low priority feature for me so it will probably take some time before i do so.

**Comment by Theo47** [comment]
Forgot to reference last commit 02dbf674f82e5849dbd3cb1abe166c87fa6e9f1b
Added.
