### ISSUE TITLE
AutoCat by store genre is backwords

### ISSUE THREAD

**Issue by CorruptComputer** [Theo47/depressurizer#40]
Things I have checked are excluded and vice-versa. I was so confused why this was being weird for like 10 minutes before I figured this out, weird bug maybe a ! somewhere it shouldn't be.

**Comment by EnemyWithin** [comment]
Do you mean the "Categories to ignore" checkbox list?

**Comment by CorruptComputer** [comment]
That seems counter intuitive then, because other menus has a category select, not a category exclude.

**Comment by EnemyWithin** [comment]
I can see where that could cause confusion.  It probably made sense at the time it was created, but doesn't match up well with the current group of AutoCats.  I'll look into switching the checkbox list to be include, instead of exclude.

**Comment by EnemyWithin** [comment]
Changed [80a505f](https://github.com/EnemyWithin/depressurizer/commit/80a505f06ee41c4ed5ac392b847b722bf19e4f27)
