### ISSUE TITLE
Translate to Russian and Ukrainian

### ISSUE THREAD

**Issue by Sinas66** [Theo47/depressurizer#41]
Can i help translate to Russian and Ukrainian?

**Comment by EnemyWithin** [comment]
Sure!  Do you have Visual Studio?

**Comment by Sinas66** [comment]
oh no xD
I think it would be just in .txt or something like that and i just write like:
Your text = My translate.
But if it necessary i can install it, but I dont know how to use it(

**Comment by EnemyWithin** [comment]
That's fine.  How about a spreadsheet on Google Docs?

**Comment by Sinas66** [comment]
Ok) it would be fine)

**Comment by EnemyWithin** [comment]
https://docs.google.com/spreadsheets/d/1m1eGEZ5SMXg7G5TrlYLoiZgdX2m1gm40Y-ryVsvtsF0/edit?usp=sharing

**Comment by EnemyWithin** [comment]
Make sure to leave {0}, {1}, etc, as is.

**Comment by Theo47** [comment]
If you haven't already started then using this may be easier. https://resxresourcemanager.codeplex.com/

**Comment by Theo47** [comment]
Although i see enemywithin already created the spreadsheet

**Comment by EnemyWithin** [comment]
"Available as VS2010/2012/2013 extension and standalone executable to support VS2008 and older"

That program looks good, but can he run it without VS?

**Comment by Theo47** [comment]
Well it says available as standalone executable so i guess so. Haven't tested it in a system without VS installed though.

**Comment by Theo47** [comment]
Assuming he can use it, it should be the same effort for him but it should save you the trouble of having to convert the spreadsheet back to the .resx files

**Comment by Theo47** [comment]
Added everything that was translated so far to depressurizer. a842676

@Sinas66 If you want to translate more in the future, tell me and i'll provide a new spreadsheet.

**Comment by Sinas66** [comment]
I'm so sorry it took so long. A lot of work and so little free time. I will continue to translate as much as possible. Waiting for new spreadsheet ;)

**Comment by Theo47** [comment]
No hurry. I just had some free time on my part so i thought i'd check what was needed to add the translations to depressurizer. Turns out we needed to have an extra column to make importing easier hence the new spreadsheet.

[New Spreadsheet](https://docs.google.com/spreadsheets/d/1N7CW2PLpSWkEKjksAC8pNbNSyAUWXuvkKpaxAEwUx1g/edit#gid=1314331253)

p.s: If you find the new column distracting then you can always right click on it and press "Hide Column".

**Comment by Theo47** [comment]
You can skip anything that sounds like an error message on your first pass. I doubt the average user sees most of those often.
