### ISSUE TITLE
Errors when opening project with VS2015

### ISSUE THREAD

**Issue by Efreak** [Theo47/depressurizer#43]
[![error](https://a.pomf.cat/trcjap.png)](https://a.pomf.cat/wpuzeo.png)

There's no references to Depressurizer.Lib.ExtToolTip and Depressurizer.Lib.ExtListView in the solution. I don't know how to fix this for a first-run; I was able to get it working by compiling the project first, then adding a reference to bin/*/es/Depressurizer.resources.dll, but oddly this changed a bunch of other files as well.

I was trying to get the scrollbars to be more in-line with the current theming, but that doesn't seem possible/easy with winforms alone; [this](https://msdn.microsoft.com/en-us/library/z57e9c2c(v=vs.110).aspx) and [this](https://msdn.microsoft.com/en-us/library/3z1hfehf(v=vs.110).aspx) are "not intended to be used directly from your code", but that doesn't mean it's impossible; other sites just say to use WPF instead of WinForms, which isn't terribly helpful, or to re-implement the scrollbars yourself.

**Comment by EnemyWithin** [comment]
Yes, you need to build the project to create the IWshRuntimeLibrary interop dll.  You definitely shouldn't need to add a reference to the Spanish resource file though?

I also tried skinning the scrollbars and ran into the same issues.  It became too much work, so I moved on to more pressing matters.  Good luck!

**Comment by Theo47** [comment]
The message Visual Studio gives for that is: "Could not find type 'Depressurizer.Lib.ExtToolTip'.  Please make sure that the assembly that contains this type is referenced.  **If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU.**". And that was the case. You just need to build the project once. You don't need to add any references or anything after you do so.

Switching to WPF just to change the scrollbar color sounds like too much work. But feel free to do so if you want.

I don't think there is anything else left to address here.
