### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VitorH1506** [Theo47/depressurizer#44]
Can I get this program to categorize one game to one category not multiple? I auto all and see same game in multiple categories.

**Comment by EnemyWithin** [comment]
Which autocats are you using?  Genre has an option to set max categories to 1.  Tags has "Tags per game", you can set that to 1.

**Comment by VitorH1506** [comment]
where I do it?

**Comment by EnemyWithin** [comment]
Edit the AutoCat and change the setting.  Use the file menu, or double-click on the AutoCat, or right-click in the AutoCat list and select "Edit Autocat".

**Comment by VitorH1506** [comment]
thank you so much
