### ISSUE TITLE
Auto-select user found local machine during Create Profile if user count is 1

### ISSUE THREAD

**Issue by sanecito** [Theo47/depressurizer#45]
During 'Create Profile' under 'Select User' in the 'Main' tab most people I suspect have only one user on the local machine. Thus for the sake of efficiency if there exists only 1 user said user should automatically be selected.

**Comment by EnemyWithin** [comment]
Fixed [80a505f](https://github.com/EnemyWithin/depressurizer/commit/80a505f06ee41c4ed5ac392b847b722bf19e4f27)
