### ISSUE TITLE
Extra Empty Column in Categorization UI

### ISSUE THREAD

**Issue by sanecito** [Theo47/depressurizer#46]
As seen in [this picture](http://i.imgur.com/ncNIVEm.png), the scrollbar can move over to the right one column despite their being no more categories. There should be no extra column when there's nothing in it. Running on Windows 10 Pro x64

**Comment by EnemyWithin** [comment]
Fixed [80a505f](https://github.com/EnemyWithin/depressurizer/commit/80a505f06ee41c4ed5ac392b847b722bf19e4f27)
