### ISSUE TITLE
Few errors with depressurizer

### ISSUE THREAD

**Issue by DARKKi** [Theo47/depressurizer#50]
I have updated and cleanly installed depressurizer few times but i still get these errors. 

First happens when i start the program (after clicking ok, it starts though) and second one comes when i press update app info in database editor. I attached screenshots of the error screens.

Sometimes after doing something the screen gets all garbled up and i have to restart but this happens rarely and i cannot pinpoint what causes it.

Starting
![depressurizer-start](https://cloud.githubusercontent.com/assets/5562502/14268086/d064e32a-fadf-11e5-876d-ffdacb7120f4.png)
Update / Database
![depressurizer-update-database](https://cloud.githubusercontent.com/assets/5562502/14268085/d04c5364-fadf-11e5-824a-88257be08b24.png)

**Comment by Theo47** [comment]
I think i have already fixed this. I was just waiting on some other stuff and this sounded like some rare bug so i hadn't released the new version yet. I'll see if everything else is working properly then make a release later today or tomorrow.

In the meantime can you check this build to see if it is actually working properly?
[Depressurizer.zip](https://github.com/Theo47/depressurizer/files/204351/Depressurizer.zip)

**Comment by DARKKi** [comment]
That build works flawlessly! Thanks!

**Comment by Theo47** [comment]
Forgot to mention that this doesn't solve the garbled up issue but without more information about that, i can't do anything to fix it.

**Comment by DARKKi** [comment]
Well it happens so rarely so no problem. If i can pinpoint what causes it i will create an issue here.

But thanks for all the support and keep up the good work! Great program!
