### ISSUE TITLE
Big bug - many games missing in depressurizer - so the can not be cataloged

### ISSUE THREAD

**Issue by dogsi64** [Theo47/depressurizer#52]
There is a big strang bug. first i delete all categories so all games stay in "uncategorized"
But many games from my libarie are not shown "Wolfenstein" "Resident evil"   ans so on.

How to uninstall the programm completely and reset all parameters. Maybe there is a big bug with localized games. I know that wolfenstein is localized for me (austria) but i dont not know if all resident evil are localized, the are also missing in listing.

**Comment by dogsi64** [comment]
i have found many games in the "ignored games" list. dont know why the all are there?

**Comment by Theo47** [comment]
Seems like you have narrowed down the cause. Were you able to solve this or do you still need help?

**Comment by dogsi64** [comment]
Thx solved - the only thing i dont know is why so many games where on the ignore list.

**Comment by Theo47** [comment]
No idea either. I never needed to work on the "ignored games" part of the code so i have no idea how that even works.
