### ISSUE TITLE
RFE - Add suffix to category name itself to show number of matches

### ISSUE THREAD

**Issue by revlisoft** [Theo47/depressurizer#53]
Request For Enhancement  - Add suffix to category name itself to show number of matches.  That way when browsing looking though the categories inside steam I can get a sense of which ones have how many games.

**Comment by Theo47** [comment]
Can;t you already do something similar with steam? [https://www.dropbox.com/s/gpb7ik3wr1ghowc/Screenshot%202016-04-26%2021.47.31.png?dl=0](https://www.dropbox.com/s/gpb7ik3wr1ghowc/Screenshot%202016-04-26%2021.47.31.png?dl=0)
