### ISSUE TITLE
Performance tanks on apps with no banner image

### ISSUE THREAD

**Issue by aaronrudkin** [Theo47/depressurizer#56]
System specs: Windows 10, 16GB ram, i5 4670K, MX200 SSD, plenty of free space, nothing else running

I downloaded depressurized to try to deal with my library and found initial performance was abysmal. I try to click on something and it registers 3-5 seconds later. Scrolling is awful. Looked around a bit and found that the issue is that the program is populating box art in the background. I don't need box art but I guess I can't turn it off for some reason so I just wait for it all to populate. My library is around 3000 games.

Once the box art populates, performance is generally better except when I scroll by a game that doesn't have a box art. This is true of a variety of weird apps like beta testing apps, prototypes, some old separate multiplayer mode apps, etc. If I move these apps to "Hidden", performance instantly recovers.

Checking task manager, Depressurizer never goes above 5% CPU and RAM usage never goes above a few hundred megabytes. I have no idea what the bottleneck is, I assuming something in the asynchronous banner loading code is blocking the UI thread.

Suggestions for fixes:
- Let people turn off box art. It makes no sense that you can turn off title and not box art.
- Check box art fetching code to see if this can be replicated elsewhere.
- Maintain a list of "weird apps" that the program knows not to get art data for.

Thanks.

**Comment by aaronrudkin** [comment]
I'm not a C# programmer, but a quick check of the code suggests that GameBanners.cs tries to look for the local cached copy of the banner using a file IO check, and then when it fails, it dispatches to Utility.cs's GetBanner method which in turn calls GetImage. It seems like you guys are set up so that GetImage will create a WebClient object. When the WebClient object fails, it writes an error to the log and then returns false to GetBanner, which then writes another error to the log and returns false. I suspect the issue is that whatever event triggers GameBanners.cs initiating the request for the file probably fires off tons of times in a row. The issue could also be in how the WebClient thread blocks performance.

Either way, you could probably either maintain a list internally of failed file loads (perhaps with a count of failures, and if the count goes over 4, simply assume no image exists and then stop requesting one) or just instead of returning false, have a default blank banner that gets returned.

**Comment by Theo47** [comment]
Yeah, i was working on some performance fixes but then real life got in the way and i kinda forgot about it.

Can you try this version and tell me how it is?

[depressurizer.zip](https://github.com/Theo47/depressurizer/files/298565/depressurizer.zip)

**Comment by aaronrudkin** [comment]
Much, much faster, and seems to be loading in images in the background no problem. Thanks.

**Comment by Theo47** [comment]
Yeah the image loading is now fully done in background.

I still want to check the issue you raised above (multiple requests been done for games that have no banners) so i will leave this issue open as a reminder to that.

**Comment by Theo47** [comment]
I don't think there is any problem anymore.
