### ISSUE TITLE
Auto-Categorizing removes custom categories

### ISSUE THREAD

**Issue by CorruptComputer** [Theo47/depressurizer#57]
I have some games that don't categorize because they have no store page, and so I add them manually to categories. However when running AutoCat again, the manually set categories get removed and the games become uncategorized once again. Which means I have to redo them all (30-40 games) and it is a pain.

Is there any way to stop this from happening?

**Comment by HunterZ** [comment]
Maybe you can add a manual database entry for them, assuming they at least have an ID?

**Comment by CorruptComputer** [comment]
A couple of them /*technically/* do, but the game was replaced by a new one. For example, Deus Ex: Human Revolution being removed and replaced with the directors cut.

**Comment by DanielJBrown** [comment]
I have run into this issue as well I had to manually assign groups to the 30 or so games that where no longer in the store. I'm too scared to clear the database again and redo everything as I don't really wan t to assign them again.

**Comment by Theo47** [comment]
From what i understand, only the genre autocat may remove categories. Is that what we are talking about?

**Comment by CorruptComputer** [comment]
I am using the Flags AutoCat. So it might have something to do with that specific thing. I use it to separate between single-player, multi-player, and Steam Achievements.

**Comment by Theo47** [comment]
I tested it to double check and the Flags AutoCat doesn't remove any categories at all.

Are you doing anything else that may be removing those categories?

**Comment by DanielJBrown** [comment]
I removed all existing categories by making a new profile, or deleting the database and starting from scratch. Then for the games without a store no categories could ever by auto allocated, so I would have to do them manually. Basically I was playing with the original version until I found this new branch (nicely done by the way!)

**Comment by Theo47** [comment]
Well i can see how making a new profile removes existing categories.
But deleting the database shouldn't remove any categories. (By database you mean the GameDB.xml.gz file, right?).

**Comment by Theo47** [comment]
As for a workaround to the main issue, you can do as HunterZ suggested and edit the game info on tools->database editor instead of directly adding the categories to the game.

For games that were replaced with other games like deus ex and deus ex director's cut, you can just add as parent id the id of the new game and it will inherit genres/flags/tags/etc from it.

For games that never existed on steam like League of Legends, Overwatch, etc this method will not work.

**Comment by DanielJBrown** [comment]
Nice i'll give that a try soon! Thanks.

**Comment by Theo47** [comment]
Well if you are actually deleting the database then this isn't going to work for you. Don't know what reason you have to delete the database though.

**Comment by CorruptComputer** [comment]
@Theo47 I'll see if I can take a video of what's happening sometime tomorrow.
