### ISSUE TITLE
Out of Memory Crash

### ISSUE THREAD

**Issue by Zhuinden** [Theo47/depressurizer#61]
```
<br />  at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
<br />   at Depressurizer.GameBanners.Grab()
<br />   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
<br />   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
<br />   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
<br />   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
<br />   at System.Threading.ThreadHelper.ThreadStart()
<br />```
<br />
<br />I have 2600 games.

**Comment by DanielJBrown** [comment]
Man I thought I had to many at 700!

**Comment by Zhuinden** [comment]
@DanielJBrown I have everything hidden that's mixed or below and I still have 1700 games left.  It's ridiculous and makes MaterialSkin throw a bunch of exceptions. It works if I don't let it terminate the app though :p

**Comment by DanielJBrown** [comment]
Is a 64 bit build possible? That should let the process go over the 2GB limit of 32bit.

**Comment by lag051183** [comment]
```
OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at Depressurizer.GameBanners.Grab()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
2000+ games

**Comment by thunderpants** [comment]
does it cache images on hard -drive ,that would save a lot of work

**Comment by thunderpants** [comment]
does it cache images on hard -drive ,that would save a lot of work

steam servers are not good when trying to load a large game library /inventory .

**Comment by Zhuinden** [comment]
@thunderpants it seems to cache it on the hard drive but it crashes anyways LOL

Although if you don't click that "the app will now close", then it doesn't crash.

**Comment by nylonee** [comment]
Yep, getting the same thing here with 1300 games =(

**Comment by Zhuinden** [comment]
@nylonee but it doesn't actually crash unless you click "OK" on termination. So the app is totally usable

**Comment by Theo47** [comment]
Can you try this version and tell me how it works? I made a quick fix to reduce the amount of ram used but not sure if that is enough.

[depressurizer.zip](https://github.com/Theo47/depressurizer/files/453936/depressurizer.zip)

**Comment by lag051183** [comment]
That did the trick, it was able to retrieve all 2400 banners without throwing an error

**Comment by Zhuinden** [comment]
@Theo47 confirmed, it doesn't seem to crash with OOM anymore

**Comment by Theo47** [comment]
Ok. I am closing this then.

**Comment by Zhuinden** [comment]
Release 0.7.1.3?

**Comment by Theo47** [comment]
Updating the game database atm. As soon as that completes i'll release it.
