### ISSUE TITLE
[request] VR Meta data categorizing

### ISSUE THREAD

**Issue by BOLL7708** [Theo47/depressurizer#63]
This is more of a feature request than an issue, I'm surprised I don't see any way to flag it as such, not sure where to post otherwise though.

There are new sections of meta data considering VR software titles, which includes which hardware is supported, tracking modes and controllers. It would be nice to be able to categorize on these values too.

**Comment by rubin110** [comment]
I started looking into something to autocategorize my library explicitly because of this. I want to create a category containing everything but VR titles for when I'm playing in big pictures mode. If this feature made it that would be great.

**Comment by Dom2077** [comment]
I believe this fits the feature request so just adding my input here.
I found this tool today when seeking a way to categorise my steam library by **seated VR** games but unfortunately that does not seem possible with the data presented in the tool.

Here is a steam filter for Seated VR games;
http://store.steampowered.com/search/?vrsupport=301

You can also find it from VR home
http://store.steampowered.com/vr/
and then it has additional categories listed;

BROWSE VR|  CATEGORIES
------------ | -------------
HTC Vive | Oculus Rift
OSVR | VR Only
Games | Software
Multi-player | Single-player
Room-Scale | Seated
Tracked Controllers | Gamepad

If it's possible to add these that would be fantastic.

**Comment by Theo47** [comment]
Added. f93ae7c4794d4f17e7ae686433498f80afe7c8eb
