### ISSUE TITLE
Show game counts next to categories in Categories list on main window

### ISSUE THREAD

**Issue by HunterZ** [Theo47/depressurizer#7]
It would be really helpful if the Categories list on the left-hand side of the main window would include a count of how many games are currently in each category.

**Comment by Theo47** [comment]
I'll take a look at that tomorrow.
Would something like this be ok or you had something better on mind?
![Game Count](http://i.imgur.com/JXzHz8i.png)

(I haven't done anything yet. I just renamed the categories to get an idea of how the feature would look.)

**Comment by HunterZ** [comment]
That's pretty much exactly what I was imagining.

**Comment by Theo47** [comment]
Ok Implemented this too and made a release. Tell me if you get any other ideas.

**Comment by Theo47** [comment]
Did a sloppy job adding this the first time so i will have to readd it.
