### ISSUE TITLE
Kaspersky marks v0.7.1.4 exe as trojan

### ISSUE THREAD

**Issue by kazerniel** [Theo47/depressurizer#73]
My Kaspersky suddenly marks the newest release exe as trojan (even though it didn't yesterday, when I first ran it):
```
File: (...)\Depressurizer.exe
Object name: Trojan-PSW.MSIL.Oligo.p
Object type: Trojan program
```

**Comment by Theo47** [comment]
Reported it to kaspersky and got this response:

>Hello,
>
>Sorry, it was a false detection. It will be fixed in the next update.
>Thank you for your help.
>
>Sincerely yours,
>Giga Alqeeq
>Malware Analyst
>_____________________
>Kaspersky Lab
>Bellevue, USA

So i guess now we just need to wait for that update.
