### ISSUE TITLE
Auto-categorize by tag not working

### ISSUE THREAD

**Issue by AndyBarron** [Theo47/depressurizer#74]
It says "Updated 236 categories," but all my games remain uncategorized.

(Windows 10 Pro, 64-bit)

**Comment by AndyBarron** [comment]
I also can't get developer/publisher to work. Genre and year seem to work fine.

**Comment by Theo47** [comment]
Apparently there aren't any tags selected by default.

So you need to right-click on it, select "edit autocats" and choose which tags you want. Ditto with developer/publisher.

I'll see about adding some defaults on the next version.

**Comment by AndyBarron** [comment]
Ahhhh I see. Thanks!

**Comment by bdefore** [comment]
I ran into this unexpectedly as well. Perhaps the README should mention that this is true for tags and flags?

**Comment by Theo47** [comment]
Added default settings for all autocats (2271d9742c55cf2cfd69fea98054255b859811b3).

Categorizing by tags, developer or publisher using the default settings will probably end up creating a few thousand categories but i couldn't find a middle ground.
