### ISSUE TITLE
[Suggestion] "Autocat by name" to avoid non-alphabet characters

### ISSUE THREAD

**Issue by r6d2** [Theo47/depressurizer#75]
First of all, thanks a lot for this nice feature! I was very glad to find it on the last release.

My suggestion as much as [0-9] characters can be grouped as "#", non-English alphabet characters (like punctuation, Japanese and other non [A-Z] characters) may be classified as "Other" as well, otherwise too many categories may be generated unnecessarily.

Thanks for considering. Cheers!

**Comment by Theo47** [comment]
Added a setting for that. 70af256c2fc7f650ba35b17312c39bd9b7ab53d7

**Comment by r6d2** [comment]
Thanks! Will try it as soon as I get home. Cheers!
