### ISSUE TITLE
Are there sth wrong with v0.7.1.4?

### ISSUE THREAD

**Issue by wellkens** [Theo47/depressurizer#76]
![depressurizer](https://cloud.githubusercontent.com/assets/22547715/20457819/844c59f2-aece-11e6-9c1a-d4258fb6c1ac.jpg)
![depressurizer1](https://cloud.githubusercontent.com/assets/22547715/20457824/c2b8124e-aece-11e6-8101-3a6716d45c4b.jpg)
I don't know why it happened on WIN10 x64……

**Comment by wellkens** [comment]
![2016-11-30_095552](https://cloud.githubusercontent.com/assets/22547715/20736738/6822d7ac-b6e3-11e6-8b7a-4b02d5c78589.jpg)

WIN7 X64, too

**Comment by Theo47** [comment]
Don't know what could be causing this.

Is this still happening? Does it happen every time you launch the program or only sometimes?

**Comment by wellkens** [comment]
Every time. The number of position changes every time too

**Comment by Theo47** [comment]
Can you go to http://requestmaker.com/, put https://www.howlongtobeatsteam.com/api/games/library/cached/all as the request url, press submit and then send me what appears on the "response body" field?

**Comment by Theo47** [comment]
You will also need to change the request type on the top of the page from POST to GET.

**Comment by wellkens** [comment]
![2017-03-10_235541](https://cloud.githubusercontent.com/assets/22547715/23802107/41479498-05ed-11e7-8378-6fe7391edd98.jpg)

Right？

**Comment by Theo47** [comment]
Yes. Can you put the text from the response body field in a txt file and upload that?

Also can you try [this version](https://www.dropbox.com/s/mfn9n0w6hrsl6rk/depressurizer.zip?dl=0)?

**Comment by wellkens** [comment]
Response Body
[Response Body.txt](https://github.com/Theo47/depressurizer/files/835701/Response.Body.txt)

**Comment by wellkens** [comment]
There isn't any warning when I run version you have updated

**Comment by Theo47** [comment]
Nice, i guess sometimes taking a shot in the dark works.

I'll consider this solved then. bc0662b409555d3bfa47e351b2f6628f88ea3fc2
