### ISSUE TITLE
Last played not being updated anymore

### ISSUE THREAD

**Issue by Remco32** [Theo47/depressurizer#79]
This metric is being track correctly in Steam itself. However, in Depressurizer the latest game I've played is stuck at 19-08-16.

**Comment by dlowe-net** [comment]
For me, the last played column is simply blank. I didn't see anything relevant in "Verbose" logs.

**Comment by Theo47** [comment]
Apparently last version when i disabled updating from local files, i ended up accidentally disabling this too.

Since next version i am re-enabling updating from local files, this should work again.

89bba046c007c8de1109e791c979c8a9a87da3d0
