### ISSUE TITLE
Scraping of games that miss the flag "Steam Achievements" but actually have achievements

### ISSUE THREAD

**Issue by Knopfdruckoffizier** [Theo47/depressurizer#8]
Is there any way of scrap games that are missing the Steam Achievements flag by accident correctly?

some examples of games that have steam achievements but no flag is provided on the store page:

8-Bit Adventures: The Forgotten Journey Remastered Edition
Acceleration of Suguri X-Edition
Alan Wake's American Nightmare
Anarchy Arcade
Angvik
Arma Tactics
Avenging Angel
...
just to name some, discovered them because i have different groups for games that "support controller" and "controller and achievements". There are quite a lot of games affected!

wonder if it is possible to not just rely on information on the store page and there is another way to check if a game got achievements or not?

**Comment by CorruptComputer** [comment]
SteamDB? Because I know it usually has more accurate information than steam. I would actually love this because there are a lot of things that done scrape currently because steam is dumb.

**Comment by Theo47** [comment]
Well games with achievements also have a "Includes x Steam Achievements" text on the steam store page so i can just check if a game has that to add the achievement flag. Could also add the number of achievements a game has to the database while i am at it.

@CorruptComputer Can you give some examples where SteamDB has more accurate information? I could take a look at using that instead if it is actually better.
Also what other things don't scrape? I could try to fix them if possible.

**Comment by Knopfdruckoffizier** [comment]
kudos :)
