### ISSUE TITLE
[Request] Language Column / Filter

### ISSUE THREAD

**Issue by Bootscreen** [Theo47/depressurizer#82]
Hy,
thx for this nice tool =)
is it possible to get a column for the game language or an option to hide all games withou a specific language?

Greetings 
Bootscreen

**Comment by bimzcy** [comment]
I need this function too, esp. the user whose native language is not English want this feature badly.

**Comment by Theo47** [comment]
Added language Autocat. 8eab129d5232118bad6710f5b8de3b001168fdac

Language Columns too but those may be less useful since a single column shows all supported languages.
