### ISSUE TITLE
Unable to select multiple categories for a game

### ISSUE THREAD

**Issue by robotpukeko** [Theo47/depressurizer#87]
I'm trying to assign two categories to a game, but the category selector only allows me to choose one at a time. The auto-assign puts two categories onto games, it's just the manual method that doesn't work. 

This happens in both the checkboxes and also the right-click menu.

**Comment by robotpukeko** [comment]
This j

**Comment by Theo47** [comment]
Perhaps the option in Tools->Single Category mode is checked?
