### ISSUE TITLE
Missing Games

### ISSUE THREAD

**Issue by DeMyztikX** [Theo47/depressurizer#88]
I'm missing a few games in Depressurizer (these were included in the old build) So far I've noticed Great Big War Game and now Gumboy Crazy Features. I'm exporting the data to XML and then converting it for use in a spreadsheet, but I double checked that Gumboy Crazy Features is NOT showing in Depressurizer but IS in my games list (both in steam and in my previous spreadsheet from export data). 

It seems if they don't have store pages they're being thrown out as garbage data (which sometimes is true, but isn't always). Great Big War Game however has a store page, but wasn't included.
Of note, Gumboy store page lands you at the correct App ID (2525) but has the name of Gumboy Crazy Adventures (which also has it's own store page at app ID 2520). Great Big War Game does not have this same issue AFAIK.

Also Missing:
Major League Baseball 2K9 (no store page) 8840
Might & Magic VI (no store page) 243380
MLB 2K10	50120
MLB® Front Office Manager	7780
RACE 07: Andy Priaulx Crowne Plaza Raceway 8650
etc. All without store pages. 

This might help building an exceptions list. http://forums.steampowered.com/forums/showthread.php?t=3071895

**Comment by Theo47** [comment]
This may have something to do with the settings on Profile->Edit Profile Info->Ignored Games.
Try checking the "Don't ignore unknown apps" or the "Bypass auto-ignore when discovering..." options and see if those games appear.

**Comment by DeMyztikX** [comment]
Used the "Don't ignore unknown apps" and checked a few games. They're listed now.
