### ISSUE TITLE
[Request] Localized/custom category names

### ISSUE THREAD

**Issue by lpchaim** [Theo47/depressurizer#89]
This is a bit of a selfish request from a non-native English speaker, so please bear with me for a while. I could be missing something, but as far as I understand it's currently not possible to set the genre/tag/flag autocats to pull from the regional Steam sites or something along those lines, right? Sure, messing with manual autocats and filters can get around that somehow, but it'd be so time consuming as to kind of defeat the point of this tool IMO. Again, I could be missing something here so please correct me if I'm wrong.
If that's unfeasible to implement, I think an option for renaming the preset tags in-app would work wonders. Maybe a new AutoCat which changes many category names at once? That way we could set it to change Action to whatever it is called locally and so on with whichever tags currently exist in our local database. Could be nice for English speakers who want some more control as well, changing FPS to First Person Shooter, for example.

**Comment by Theo47** [comment]
Like that idea.

e682a0fec7618183cc04b4524167a1b81b5ebb58
Added a new setting to have Depressurizer pull info from regional Steam sites instead.

**Comment by lpchaim** [comment]
Thanks a lot, sounds perfect!
