### ISSUE TITLE
Selecting/unselecting category in category box reloads list, loses position

### ISSUE THREAD

**Issue by wickles** [Theo47/depressurizer#9]
Hope it makes sense. This didn't happen in rallion's last version 0.6.1.0

**Comment by Theo47** [comment]
Do you mean when you add/remove a category to/from a game by clicking the checkbox in the category list below the game list or when you switch to another category by clicking one of the categories on the category list to the left of the game list?

**Comment by wickles** [comment]
The first one, adding/removing the checkbox below the game list. Can you reproduce this?

**Comment by Theo47** [comment]
Yes i can reproduce it. It seems that it also doesn't happen on my version 0.6.2.1 and i haven't done many changes since then so it should be easy to figure out what i did wrong.

**Comment by Theo47** [comment]
Fixed.

**Comment by wickles** [comment]
Awesome. Will you put up new binaries or holding off for a while?

**Comment by aeberhardo** [comment]
Very nice, I'm also interested in the updated binaries. Also a big thank-you for all the work you put into this!

**Comment by Theo47** [comment]
Thanks. I am planning to wait till i am done with all of the open issues (except my initial 3 which are frozen for now) as well as some additional testing to make sure my updates are working correctly before making a new release.

Here are the updated binaries: https://dl.dropboxusercontent.com/u/46188332/depressurizer.zip

**Comment by aeberhardo** [comment]
Cool, thank you very much!
