### ISSUE TITLE
Not picking up any changes made in Steam itself. 

### ISSUE THREAD

**Issue by thefunkygibbon** [Theo47/depressurizer#90]
For example, I add a game to a category within Steam... or create a new category and add some games to it within Steam.  Exit Steam
Open depressurizer and it does not show the new category or the game added to the category. 

am i doing something wrong or is it a bug?

**Comment by skapytek** [comment]
This is also happening for me. Im not sure if this is a bug or if it is not possible to track it atm with depressurizer.

**Comment by shinomory** [comment]
Works for me, make sure under your profile settings (Profile, Edit Profile Info or Ctrl+P) that "Automatically import categories from Steam on load" is checked on the options tab. It's by profile, not an application-wide setting, and I think by default it might be unchecked.

**Comment by Theo47** [comment]
It is as shinomory said. If you want it to automatically update your changes from Steam, you have to check the setting that shinomory said above.

Else you can manually sync your changes from Steam by pressing Profile->Import Steam Config.
