### ISSUE TITLE
HOW Do I LAUNCH Depressurizer?

### ISSUE THREAD

**Issue by OuterSpaceHoliday** [Theo47/depressurizer#95]
I have tried the files here, but there is no .exe, and I have installed with choco, but I have no idea how to launch after that. Please help me! I am pretty tech savvy, but this is blowing my mind!!! I used depressurizer years ago and it was awesome! Now it seems like a convoluted mess just to use it. :(

**Comment by CorruptComputer** [comment]
I'm not sure I understand your issue, did you download the wrong thing? https://github.com/Theo47/depressurizer/releases

**Comment by OuterSpaceHoliday** [comment]
Holy crap! Thank you! Every link takes me to the source files and I could not find a release anywhere! I spent HOURS trying to figure this out.
