### ISSUE TITLE
Fatal error loading profile from file

### ISSUE THREAD

**Issue by salattu** [Theo47/depressurizer#98]
Launched Depressurizer for the first time on a Windows 10 computer. Located Steam. Cancelled new profile creation. Attempted to load profile to try and 'import' a profile created on a different computer. Received "A fatal error has occurred in Json.NET. The program will now terminate."

Error info:
NullReferenceException: object reference not set to an instance of an object.
Depressurizer.FormMain.LoadProfile()
Depressurizer.FormMain.menu_File_LoadProfile_Click(Object sender, EventArgs e)
System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
System.Windows.Forms.Control.WndProc(Message& m)
System.Windows.Forms.ScrollableControl.WndProc(Message& m)
System.Windows.Forms.ToolStrip.WndProc(Message& m)
System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Theo47** [comment]
Same issue as https://github.com/Theo47/depressurizer/issues/78.

Fixed (06c45d41b08b70ccb1f64ef2db91b830240005b2).

I'll probably release a new version in a few days. In the meantime you can follow the workaround suggested in the other thread (or compile the code yourself).
